### ISSUE TITLE
Discord Threads

### ISSUE THREAD

**Issue by pccross** [ademarc/langchain-discord-chatbot#1]
Really liked how this project was implemented.   How difficult would it be to adapt to Discord Threads, as in the current form, you can have multiple users submitting to chatbot and kind of squashing over each other?

**Comment by ademarc** [comment]
Thank you for your kind words, I think the bot's private message feature can be leveraged to support multiple users, you can let me know if you've encountered issues with that. 

Also, adapting to Discord Threads sounds like a fantastic idea and shouldn't be much trouble (at least on a high level).

**Comment by ademarc** [comment]
@pccross ,

Thank you for bringing this to my attention. I have made updates to the bot to address the concerns you raised. As of #2 , the bot now only responds to messages where it is directly mentioned. This update should prevent the bot from interrupting conversations in the main channel and handle interactions with multiple users more gracefully.

I'll be closing this issue now as the changes have been implemented. Please feel free to reopen it or create a new issue if you encounter any more problems or have additional feedback.
